### ISSUE TITLE
Flutter project's `pubspec.lock` will get warning "Use a smart opening quote here: <suggestion>“</suggestion>."

### ISSUE THREAD

**Issue by jerryzhoujw** [languagetool-language-server/vscode-languagetool#26]
In `pubspec.lock` file, when I enable vscode extension **`English Support for LanguageTool`**, it will give `warning` for every `double quotation marks(")`:

### part of `pubspec.lock` file
```
packages:
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.36.4"
  analyzer_plugin:
    dependency: transitive
    description:
      name: analyzer_plugin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.1-alpha.8"
    ...
```

### One of the warning detail is as bellow:
```
{
	"resource": "[Flutter_Project_Path]/pubspec.lock",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "Use a smart opening quote here: <suggestion>“</suggestion>.",
	"source": "LanguageTool: Smart quotes (“”)",
	"startLineNumber": 8,
	"startColumn": 12,
	"endLineNumber": 8,
	"endColumn": 13
}
```
